[package]
name = "task_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.25"
rdev = "0.5"
csv = "1.3"
chrono = "0.4"
opener = "0.5"
tray-icon = "0.6"
image = "0.24"
device_query = "1.1"

